# Use an official Node.js runtime as the base image- this is latest Alpine
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory - "app" is the working directory
COPY package.json ./
COPY ./ ./

# Install dependencies
RUN npm install

# Build the React app
RUN npm run build

# Expose the port your React app runs on in the container
EXPOSE 3000
EXPOSE 80

# Command to run the React app
CMD ["npm", "start"]
