# Use an official Node.js runtime as the base image- this is latest Alpine
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory - "app" is the working directory
COPY package.json ./
COPY ./ ./

# Install dependencies
RUN npm install

# Build the React app
RUN npm run build

# Stage 2 - Production Environment
FROM nginx:alpine

# Copy build output from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Command to run NGINX
CMD ["nginx", "-g", "daemon off;"]
