# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app/

# Copy package.json and package-lock.json to the working directory
COPY public/ /app/public
COPY src/ /app/src
COPY package.json /app/

# Install dependencies
RUN npm install

# Expose the port your React app runs on
EXPOSE 3000

# Command to run the React app
CMD ["npm", "start"]
