apiVersion: v1
kind: Service
metadata:
  name: demoreact-service
spec:
  selector:
    app: demoreact
  ports:
  - name: http  
    port: 80
    targetPort: 3003
    protocol: TCP
  type: LoadBalancer
